#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');

/**
 * Setup script for NLP Question Generator
 */
class SetupManager {
    constructor() {
        this.configDir = path.join(process.cwd(), '.nlp-qg');
        this.envFile = path.join(process.cwd(), '.env');
        this.configFile = path.join(this.configDir, 'config.json');
    }

    /**
     * Create configuration directory and files
     */
    async createConfig() {
        // Create .nlp-qg directory
        if (!fs.existsSync(this.configDir)) {
            fs.mkdirSync(this.configDir, { recursive: true });
        }

        // Create default config
        const defaultConfig = {
            "defaultProvider": "gemini",
            "currentProvider": "gemini",
            "providers": {
                "gemini": {
                    "model": "gemini-1.5-flash",
                    "temperature": 0.7,
                    "maxRetries": 3
                },
                "openai": {
                    "model": "gpt-3.5-turbo",
                    "temperature": 0.7,
                    "maxRetries": 3
                },
                "anthropic": {
                    "model": "claude-3-5-sonnet-20241022",
                    "temperature": 0.7,
                    "maxRetries": 3
                },
                "deepseek": {
                    "model": "deepseek-chat",
                    "temperature": 0.7,
                    "maxRetries": 3
                }
            }
        };

        fs.writeFileSync(this.configFile, JSON.stringify(defaultConfig, null, 2));
        console.log('✓ Created default configuration');
    }

    /**
     * Create .env file with template
     */
    async createEnvFile() {
        const envTemplate = `# NLP Question Generator Environment Variables
# Copy this file to .env and add your API keys

# Google Gemini API Key
GEMINI_API_KEY=

# OpenAI API Key  
OPENAI_API_KEY=

# Anthropic API Key
ANTHROPIC_API_KEY=

# DeepSeek API Key
DEEPSEEK_API_KEY=

# Server Configuration
PORT=3000
NODE_ENV=development
`;

        fs.writeFileSync(this.envFile, envTemplate);
        console.log('✓ Created .env template file');
    }

    /**
     * Interactive API key configuration
     */
    async setupApiKeys() {
        const rl = readline.createInterface({
            input: process.stdin,
            output: process.stdout
        });

        const question = (text) => new Promise((resolve) => rl.question(text, resolve));

        console.log('\n🔑 API Key Configuration');
        console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
        console.log('You can skip this step and configure API keys later.\n');

        const providers = [
            { name: 'gemini', label: 'Google Gemini', key: 'GEMINI_API_KEY' },
            { name: 'openai', label: 'OpenAI', key: 'OPENAI_API_KEY' },
            { name: 'anthropic', label: 'Anthropic Claude', key: 'ANTHROPIC_API_KEY' },
            { name: 'deepseek', label: 'DeepSeek AI', key: 'DEEPSEEK_API_KEY' }
        ];

        let envContent = `# NLP Question Generator Environment Variables
# Generated by setup script

`;

        for (const provider of providers) {
            const answer = await question(`${provider.label} API Key (press Enter to skip): `);
            if (answer.trim()) {
                envContent += `${provider.key}=${answer.trim()}\n`;
                console.log(`✓ ${provider.label} API key configured`);
            } else {
                envContent += `${provider.key}=\n`;
                console.log(`⚬ ${provider.label} API key skipped`);
            }
        }

        envContent += `
# Server Configuration
PORT=3000
NODE_ENV=development
`;

        // Update .env file
        fs.writeFileSync(this.envFile, envContent);
        console.log('\n✓ API keys saved to .env file');

        rl.close();
    }

    /**
     * Create uploads directory
     */
    async createUploadsDir() {
        const uploadsDir = path.join(process.cwd(), 'uploads');
        if (!fs.existsSync(uploadsDir)) {
            fs.mkdirSync(uploadsDir, { recursive: true });
            console.log('✓ Created uploads directory');
        }
    }

    /**
     * Run full setup
     */
    async run() {
        console.log('NLP Question Generator Setup\n');
        console.log('This will help you configure the application for first use.\n');

        await this.createConfig();
        await this.createEnvFile();
        await this.createUploadsDir();

        console.log('\n🔧 Configuration Setup Complete!\n');
        console.log('Next steps:');
        console.log('1. Add your API keys to the .env file');
        console.log('2. Run: npm start');
        console.log('3. Or configure API keys now? (y/N)');

        const rl = readline.createInterface({
            input: process.stdin,
            output: process.stdout
        });

        const answer = await new Promise((resolve) => rl.question('Configure API keys now? (y/N): ', resolve));
        rl.close();

        if (answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes') {
            await this.setupApiKeys();
        }

        console.log('\n🎉 Setup complete! You can now run "npm start" to start the server.');
        console.log('💡 Use "node cli/cli.js config" for interactive configuration.\n');
    }
}

// Run setup if called directly
if (require.main === module) {
    const setup = new SetupManager();
    setup.run().catch(error => {
        console.error('❌ Setup failed:', error);
        process.exit(1);
    });
}

module.exports = SetupManager;