#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');

/**
 * Simple Configuration Manager for NLP Question Generator
 * Manages API keys in .env file
 */
class ConfigManager {
    constructor() {
        this.envFile = path.join(process.cwd(), '.env');
        this.envExampleFile = path.join(process.cwd(), 'env.example');
        
        this.rl = readline.createInterface({
            input: process.stdin,
            output: process.stdout
        });
    }

    /**
     * Read current .env file
     */
    readEnv() {
        const env = {};
        
        if (fs.existsSync(this.envFile)) {
            const content = fs.readFileSync(this.envFile, 'utf8');
            const lines = content.split('\n');
            
            for (const line of lines) {
                const trimmed = line.trim();
                if (trimmed && !trimmed.startsWith('#')) {
                    const [key, ...valueParts] = trimmed.split('=');
                    if (key) {
                        env[key.trim()] = valueParts.join('=').trim();
                    }
                }
            }
        }
        
        return env;
    }

    /**
     * Write .env file
     */
    writeEnv(env) {
        const lines = [
            '# NLP Question Generator Environment Variables',
            '# Generated by config tool',
            '',
            '# API Keys',
            `GEMINI_API_KEY=${env.GEMINI_API_KEY || ''}`,
            `OPENAI_API_KEY=${env.OPENAI_API_KEY || ''}`,
            `ANTHROPIC_API_KEY=${env.ANTHROPIC_API_KEY || ''}`,
            `DEEPSEEK_API_KEY=${env.DEEPSEEK_API_KEY || ''}`,
            `KIMI_API_KEY=${env.KIMI_API_KEY || ''}`,
            `KIMICN_API_KEY=${env.KIMICN_API_KEY || ''}`,
            '',
            '# Default AI Provider',
            '# Options: gemini, openai, anthropic, deepseek, kimi, kimicn',
            `DEFAULT_PROVIDER=${env.DEFAULT_PROVIDER || 'gemini'}`,
            '',
            '# Server Configuration',
            `PORT=${env.PORT || '3000'}`,
            `NODE_ENV=${env.NODE_ENV || 'development'}`,
            ''
        ];
        
        fs.writeFileSync(this.envFile, lines.join('\n'));
    }

    /**
     * Initialize configuration
     */
    async init() {
        console.log('NLP Question Generator - API Key Configuration\n');
        
        // Create .env if it doesn't exist
        if (!fs.existsSync(this.envFile)) {
            if (fs.existsSync(this.envExampleFile)) {
                fs.copyFileSync(this.envExampleFile, this.envFile);
                console.log('✓ Created .env file from template\n');
            } else {
                this.writeEnv({});
                console.log('✓ Created new .env file\n');
            }
        }

        await this.showMainMenu();
    }

    /**
     * Show main menu and handle user input
     */
    async showMainMenu() {
        const menu = `
┌─────────────────────────────────────────────────────┐
│    NLP Question Generator - API Key Configuration    │
├─────────────────────────────────────────────────────┤
│  1. View Current Configuration                      │
│  2. Configure API Keys                              │
│  3. Set Default AI Provider                         │
│  4. Help & Documentation                            │
│  0. Exit                                            │
└─────────────────────────────────────────────────────┘
`;

        console.log(menu);
        
        const choice = await this.question('Select an option (0-4): ');
        
        switch (choice.trim()) {
            case '1':
                await this.viewConfig();
                break;
            case '2':
                await this.configureApiKeys();
                break;
            case '3':
                await this.setDefaultProvider();
                break;
            case '4':
                await this.showHelp();
                break;
            case '0':
                console.log('Goodbye! Restart your server to apply changes.');
                this.rl.close();
                process.exit(0);
            default:
                console.log('❌ Invalid option. Please try again.\n');
                await this.showMainMenu();
        }
    }

    /**
     * View current configuration
     */
    async viewConfig() {
        console.log('\nCurrent Configuration:\n');
        
        const env = this.readEnv();
        
        // Show default provider
        const defaultProvider = env.DEFAULT_PROVIDER || 'gemini';
        console.log(`Default AI Provider: ${defaultProvider}\n`);
        
        // Show API key status
        console.log('API Key Status:\n');
        
        const providers = {
            'GEMINI_API_KEY': 'Google Gemini',
            'OPENAI_API_KEY': 'OpenAI GPT',
            'ANTHROPIC_API_KEY': 'Anthropic Claude',
            'DEEPSEEK_API_KEY': 'DeepSeek',
            'KIMI_API_KEY': 'Kimi AI Global (Moonshot)',
            'KIMICN_API_KEY': 'Kimi AI China (Moonshot CN)'
        };

        for (const [key, name] of Object.entries(providers)) {
            const value = env[key];
            if (value && value.length > 0) {
                const masked = value.substring(0, 8) + '*'.repeat(Math.max(0, value.length - 8));
                console.log(`  ✓ ${name}: ${masked}`);
            } else {
                console.log(`  ❌ ${name}: Not configured`);
            }
        }
        
        console.log(`\nConfiguration file: ${this.envFile}`);
        console.log();

        await this.backToMenu();
    }

    /**
     * Configure API keys for providers
     */
    async configureApiKeys() {
        console.log('\nConfigure API Keys\n');
        console.log('Enter API keys (or press Enter to skip)\n');
        
        const env = this.readEnv();
        
        const providers = {
            'GEMINI_API_KEY': 'Google Gemini',
            'OPENAI_API_KEY': 'OpenAI GPT',
            'ANTHROPIC_API_KEY': 'Anthropic Claude',
            'DEEPSEEK_API_KEY': 'DeepSeek',
            'KIMI_API_KEY': 'Kimi AI Global (Moonshot)',
            'KIMICN_API_KEY': 'Kimi AI China (Moonshot CN)'
        };
        
        for (const [envKey, name] of Object.entries(providers)) {
            const currentKey = env[envKey];
            
            if (currentKey && currentKey.length > 0) {
                const masked = currentKey.substring(0, 8) + '*'.repeat(Math.max(0, currentKey.length - 8));
                console.log(`\n${name}:`);
                console.log(`Current: ${masked}`);
            } else {
                console.log(`\n${name}: Not configured`);
            }
            
            const newKey = await this.question(`Enter new API key (or press Enter to keep current): `);
            
            if (newKey.trim()) {
                env[envKey] = newKey.trim();
                console.log(`✓ ${name} API key updated`);
            }
        }

        this.writeEnv(env);
        console.log('\n✓ Configuration saved to .env file');
        console.log('⚠ Restart your server for changes to take effect\n');
        
        await this.backToMenu();
    }



    /**
     * Set default AI provider
     */
    async setDefaultProvider() {
        console.log('\nSet Default AI Provider\n');
        
        const env = this.readEnv();
        
        // Get list of configured providers
        const configuredProviders = [];
        const providerMap = {
            'GEMINI_API_KEY': 'gemini',
            'OPENAI_API_KEY': 'openai',
            'ANTHROPIC_API_KEY': 'anthropic',
            'DEEPSEEK_API_KEY': 'deepseek',
            'KIMI_API_KEY': 'kimi',
            'KIMICN_API_KEY': 'kimicn'
        };
        
        const providerNames = {
            'gemini': 'Google Gemini',
            'openai': 'OpenAI GPT',
            'anthropic': 'Anthropic Claude',
            'deepseek': 'DeepSeek',
            'kimi': 'Kimi AI Global (Moonshot)',
            'kimicn': 'Kimi AI China (Moonshot CN)'
        };
        
        for (const [envKey, providerKey] of Object.entries(providerMap)) {
            if (env[envKey] && env[envKey].trim().length > 0) {
                configuredProviders.push(providerKey);
            }
        }
        
        if (configuredProviders.length === 0) {
            console.log('❌ No providers configured. Please configure API keys first.\n');
            await this.backToMenu();
            return;
        }
        
        const currentDefault = env.DEFAULT_PROVIDER || 'gemini';
        console.log(`Current default provider: ${providerNames[currentDefault] || currentDefault}\n`);
        console.log('Available providers:\n');
        
        configuredProviders.forEach((provider, index) => {
            const isCurrent = provider === currentDefault ? ' (current)' : '';
            console.log(`  ${index + 1}. ${providerNames[provider]}${isCurrent}`);
        });
        
        console.log('  0. Cancel\n');
        
        const choice = await this.question(`Select default provider (0-${configuredProviders.length}): `);
        const choiceNum = parseInt(choice.trim());
        
        if (choiceNum === 0) {
            console.log('Cancelled.\n');
            await this.backToMenu();
            return;
        }
        
        if (choiceNum > 0 && choiceNum <= configuredProviders.length) {
            const selectedProvider = configuredProviders[choiceNum - 1];
            env.DEFAULT_PROVIDER = selectedProvider;
            this.writeEnv(env);
            console.log(`\n✓ Default provider set to: ${providerNames[selectedProvider]}`);
            console.log('⚠ Restart your server for changes to take effect\n');
        } else {
            console.log('❌ Invalid selection.\n');
        }
        
        await this.backToMenu();
    }

    /**
     * Show help and documentation
     */
    async showHelp() {
        console.log(`
Help & Documentation

Supported AI Providers:
  • Google Gemini - Get free API key: https://makersuite.google.com/app/apikey
  • OpenAI GPT - Get API key: https://platform.openai.com/api-keys
  • Anthropic Claude - Get API key: https://console.anthropic.com/
  • DeepSeek - Get API key: https://platform.deepseek.com/
  • Kimi AI Global - Get API key: https://platform.moonshot.ai/
  • Kimi AI China - Get API key: https://platform.moonshot.cn/

Configuration:
  • API keys are stored in .env file in your project root
  • Never commit .env file to version control
  • Restart server after changing API keys

How to Use:
  1. Get API key from provider website (see links above)
  2. Run 'npm run config' to configure
  3. Enter your API key when prompted
  4. Restart server: 'npm start'

API Endpoints:
  • POST /api/generate - Generate questions from text
  • POST /api/generate-from-files - Generate from uploaded files
  • GET /api/providers - List available providers
  • POST /api/switch-provider - Switch between providers

Tips:
  • Free tier API keys work great for testing
  • Gemini (Google) has generous free tier
  • All providers have automatic fallback and retry logic
  • Check README_TROUBLESHOOTING.md for common issues
`);

        await this.backToMenu();
    }

    /**
     * Ask a question
     */
    async question(prompt) {
        return new Promise((resolve) => {
            this.rl.question(prompt, (answer) => {
                resolve(answer);
            });
        });
    }

    /**
     * Wait for user to press Enter to continue
     */
    async backToMenu() {
        console.log('\nPress Enter to continue...');
        await this.question('> ');
        await this.showMainMenu();
    }
}

// Run CLI if called directly
if (require.main === module) {
    const configManager = new ConfigManager();
    configManager.init().catch(error => {
        console.error('Configuration failed:', error);
        process.exit(1);
    });
}

module.exports = ConfigManager;